version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3_malware'
    tty: true
    volumes:
      - ./share:/Workspace
  gpu:
    build: ./gpu
    container_name: tensorflow_gpu
    tty: true
    volumes:
      - ./share:/Workspace
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [utility, compute, video]
